### PR TITLE
add code for snakemake lesson

### PR DESCRIPTION
**Pull request by psteinb**
Up until here, the code examples to do the snakemake parts are hidden in a versioned *.tar.gz/*.zip file inside [files](https://github.com/hpc-carpentry/hpc-python/tree/gh-pages/files). This PR exposes this code in order to make it more testable. In this manor, the snakemake code can later be integrated with CI tools like travis, appveyor and others.

### CODE REVIEW

**Comment by tkphd** [comment]
Is there a reason to retain the binary `tar.gz` files?

**Comment by psteinb** [comment]
well, that is possibly due to my ignorance. The binary files are retained in order to be able to download them later. If there is a way to make the tar.gz/zip files an artifact during a CI build, which can then be part of a release process. We could have the website point to that artifact online. Ideas?

**Comment by tkphd** [comment]
Ah-ha, I see: `snakemake-lesson.zip` is referred to in `index`, so that file (at least) should be retained for ease of distribution.

**Review by tkphd — APPROVED** [review]
Simple extraction of the files from `files/snakemake-lesson.zip`, with a new rule to build that file from modified sources as necessary. LGTM.

**Pull request merged**
