### PR TITLE
Typos and clarifications

### PR DESCRIPTION
**Pull request by andrewsanchez**

### CODE REVIEW

**Comment by tkphd** [comment]
Hi @andrewsanchez, thanks for the contribution! The conversion from Make to Snakemake definitely improves consistency, and clears up a lot of confusion. Also, kudos for making atomic commits! It's much appreciated.

While the replacement of `make` with `snakemake` is good, I have reservations about some of your other changes, as follows:

- 6271114: The lesson starts out with a Snakefile that sets `books/isles.txt` as the input file. It's definitely useful to `head` the file to (a) make sure it exists and (b) get a sense of what it contains.
- a46a9ee: Since it's a proper noun in prose, Snakemake should be capitalized .
- 8b0c2e1: Please explain your reasoning. Using `rm -f`, the command will succeed whether the named files exist or not.
- 12f91a3: Curly braces in these Markdown files denote Liquid variables, which Jekyll substitutes at build time. The text inside the braces you switched are not Liquid variables, so the change slightly decreases maintainability. With that being said, a case could certainly be made for removing those square braces entirely, since the dummy file names make it clear that they are to be changed in practice.
- b3df3dd: The original text used `make`, the executable. The substitution uses `Snakemake`, which is not an executable.
- e251550: At [snakemake.io:851](https://bitbucket.org/snakemake/snakemake/src/7471ce1f2501bded574510011c9d61184f6be7a5/snakemake/io.py?at=master&fileviewer=file-view-default#io.py-851), `Wildcard` is declared as a namedtuple object. It is not special Snakemake oil.
- 6307416: The proposed language does not clarify anything. It is also a grammatically incorrect clause following *Add new rules and update existing rules to:*.
- 4029489: Commas in the original text imposed structure on the sentence. Removing them makes the sentence a confusing run-on. The proposed additional sentence reiterates the existing language, without clarifying.
  
Thanks again for looking over this course and working to improve it.

**Comment by andrewsanchez** [comment]
Hi, @tkphd.  Thanks for your review!  Do you have a strong preference for whether I reply here versus commenting directly on the individual commits?

**Comment by tkphd** [comment]
@jstaf, are you able to review this PR?

**Comment by andrewsanchez** [comment]
Aren't you able to review/approve, @tkphd?  I'll address your latest comments and put commit my finishing touches in the next few days.

**Comment by ChristinaLK** [comment]
@andrewsanchez I think you're the only one with merge permissions in this repository (besides me, and my access is mostly because I'm the de-facto Github Permissions Granter).

If you're uncomfortable merging your own PR, let me know, and I can merge after it's been reviewed and approved.

**Review by tkphd — APPROVED** [review]

**Review by psteinb — APPROVED** [review]
Thanks for finding and fixing all these.

**Comment by psteinb** [comment]
.Turns out I have merge permissions. ;-) Thanks @andrewsanchez for the contribution and @tkphd for the review

**Pull request merged**
